### ISSUE TITLE
 neoqs fails to import on codesandbox while qs works

### ISSUE THREAD

**Issue by mhdcodes** [PuruVJ/neoqs#1]
## Description

While trying `neoqs` for some examples I noticed that it does not load on codesandbox, to make sure it is not a codesandbox issue I tried it with `qs`. that worked as expected, so might be worth a look as it might affect other environment?

![image](https://github.com/user-attachments/assets/fb669cfb-a046-4f95-9476-779dc174faf6)

## Example
https://codesandbox.io/p/sandbox/neoqs-example-gnn6vg

**Comment by PuruVJ** [comment]
Initial response here: https://x.com/puruvjdev/status/1821892070107165134

![CleanShot 2024-08-09 at 18 28 20](https://github.com/user-attachments/assets/3addc98e-0937-4f64-a18e-781e32d7e7f2)

Lets continue the conversation here

**Comment by mhdcodes** [comment]
so apparently this solves the issue but not sure why. https://github.com/codesandbox/codesandbox-client/issues/7290

```
devDependencies: {
    "@babel/core": "7.2.0"
},
```

**Comment by PuruVJ** [comment]
IG I'll close the issue then. Thanks a lot for reporting it!
